export let allSkills = [
    {selected: false, name: "HTML"},
    {selected: false, name: "CSS"},
    {selected: false, name: "Javascript"},
    {selected: false, name: "Typescript"},
    {selected: false, name: "ASP.Net"},
    {selected: false, name: "C/C++"},
    {selected: false, name: "Python"},
    {selected: false, name: "Django"},
    {selected: false, name: "Flask"},
    {selected: false, name: "React"},
    {selected: false, name: "React Native"},
    {selected: false, name: "Angular"},
    {selected: false, name: "Vue"},
    {selected: false, name: "Docker"},
    {selected: false, name: "Kubernetes"},
    {selected: false, name: "AWS"},
    {selected: false, name: "C#"},
    {selected: false, name: "GoLang"},
    {selected: false, name: "Node"},
    {selected: false, name: "Express"},
    {selected: false, name: "Testing"},
    {selected: false, name: "Flutter"},
    {selected: false, name: "Objective-C"},
    {selected: false, name: "Linux"},
    {selected: false, name: "OOP"},
    {selected: false, name: "Java"},
    {selected: false, name: "PHP"},
    {selected: false, name: "SQL"},
    {selected: false, name: "MongoDb"},
    {selected: false, name: "Mongoose"},
    {selected: false, name: "Azure"},
    {selected: false, name: "Ruby"},
    {selected: false, name: "SASS"},
    {selected: false, name: "gRPC"},
];  